-------------------- Log Start | Tue Mar 11 19:19:00 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################

Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 182

System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: add5f1c6
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.4
  total_memory: 880328
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73685
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'network-online.target', 'sysinit.target']
**After=['systemd-journald.socket', 'system.slice', 'network-online.target', 'sysinit.target', 'klipper.service', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['-.mount', 'klipper-mcu.service', 'network-online.target', 'basic.target', 'system.slice', 'systemd-journald.socket', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
Klipper Version: v0.12.0-85-gd785b396a-dirty
2025-03-12 00:49:00,390 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:00,943 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:01,500 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:02,051 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:02,614 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:02,619 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:02,670 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:03,231 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:03,788 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:04,366 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:04,944 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:04,947 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:05,033 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:05,589 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:06,141 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:06,702 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:07,256 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 00:49:07,260 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:00,387 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:00,937 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:01,507 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:02,083 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:02,646 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:02,648 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:02,692 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:03,258 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:03,807 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:04,359 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:04,907 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:04,910 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:04,959 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:05,512 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:06,059 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:06,610 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:07,191 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:19:07,197 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:00,390 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:00,937 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:01,513 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:02,066 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:02,621 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:02,624 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:02,670 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:03,225 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:03,774 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:04,332 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:04,897 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:04,901 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:04,956 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:05,510 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:06,062 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:06,651 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:07,228 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 01:49:07,235 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:00,377 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:00,939 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:01,490 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:02,042 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:02,632 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:02,637 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:02,689 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:03,240 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:03,811 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:04,357 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:04,904 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:04,907 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:04,961 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:05,508 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:06,064 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:06,611 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:07,159 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:19:07,162 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:00,387 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:00,941 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:01,492 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:02,043 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:02,622 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:02,627 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:02,681 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:03,229 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:03,782 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:04,340 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:04,890 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:04,895 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:04,944 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:05,499 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:06,057 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:06,606 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:07,161 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 02:49:07,163 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:00,376 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:00,932 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:01,479 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:02,036 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:02,585 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:02,589 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:02,634 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:03,200 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:03,755 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:04,316 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:04,893 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:04,898 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:04,956 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:05,505 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:06,058 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:06,609 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:07,166 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:19:07,169 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:00,382 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:00,936 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:01,492 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:02,049 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:02,600 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:02,603 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:02,648 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:03,206 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:03,760 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:04,315 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:04,873 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:04,876 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:04,923 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:05,503 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:06,069 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:06,625 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:07,175 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 03:49:07,179 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:00,417 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:00,999 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:01,555 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:02,109 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:02,659 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:02,663 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:02,709 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:03,271 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:03,829 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:04,403 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:04,956 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:04,958 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:05,011 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:05,567 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:06,139 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:06,693 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:07,244 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:19:07,247 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:00,381 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:00,932 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:01,499 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:02,083 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:02,637 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:02,640 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:02,685 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:03,246 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:03,799 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:04,346 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:04,894 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:04,899 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:04,942 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:05,492 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:06,053 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:06,607 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:07,180 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 04:49:07,185 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:00,412 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:00,968 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:01,516 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:02,067 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:02,614 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:02,616 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:02,674 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:03,236 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:03,815 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:04,371 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:04,921 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:04,924 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:04,970 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:05,542 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:06,091 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:06,640 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:07,188 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:19:07,190 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:00,411 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:00,960 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:01,513 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:02,063 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:02,612 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:02,615 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:02,674 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:03,222 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:03,785 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:04,334 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:04,892 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:04,896 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:04,943 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:05,532 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:06,089 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:06,641 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:07,196 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 05:49:07,199 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:00,391 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:00,942 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:01,495 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:02,049 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:02,609 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:02,611 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:02,658 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:03,207 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:03,762 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:04,319 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:04,880 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:04,883 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:04,935 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:05,528 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:06,091 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:06,643 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:07,194 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:19:07,197 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:00,391 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:00,940 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:01,506 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:02,057 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:02,606 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:02,609 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:02,657 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:03,213 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:03,770 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:04,321 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:04,872 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:04,876 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:04,928 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:05,502 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:06,082 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:06,641 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:07,188 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 06:49:07,191 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:00,393 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:00,944 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:01,527 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:02,079 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:02,645 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:02,651 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:02,699 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:03,270 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:03,825 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:04,386 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:04,940 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:04,944 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:04,998 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:05,545 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:06,112 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:06,687 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:07,262 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:19:07,266 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:00,388 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:00,934 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:01,483 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:02,030 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:02,604 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:02,608 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:02,678 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:03,241 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:03,788 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:04,338 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:04,890 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:04,893 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:04,943 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:05,506 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:06,060 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:06,613 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:07,163 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 07:49:07,165 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:00,417 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:00,976 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:01,530 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:02,077 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:02,632 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:02,635 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:02,702 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:03,259 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:03,818 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:04,373 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:04,925 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:04,928 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:04,983 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:05,578 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:06,167 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:06,728 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:07,318 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:19:07,322 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:00,393 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:00,956 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:01,505 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:02,057 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:02,613 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:02,616 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:02,662 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:03,224 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:03,775 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:04,341 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:04,892 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:04,894 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:04,946 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:05,519 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:06,072 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:06,620 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:07,172 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 08:49:07,176 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:00,397 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:00,948 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:01,498 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:02,053 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:02,618 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:02,622 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:02,673 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:03,265 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:03,828 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:04,389 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:04,948 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:04,951 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:05,000 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:05,553 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:06,112 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:06,667 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:07,246 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:19:07,249 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:00,406 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:00,964 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:01,532 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:02,092 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:02,645 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:02,648 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:02,706 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:03,302 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:03,882 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:09,448 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:09,450 [ioloop.py:_run_callback()] - Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7fac3baa60>, <Task finished name='Task-9415735' coro=<_HTTPConnection.run() done, defined at /home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py:290> exception=SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')>)
Traceback (most recent call last):
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 287, in <lambda>
    gen.convert_yielded(self.run()), lambda f: f.result()
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
  File "/home/om/moonraker-env/lib/python3.9/site-packages/tornado/iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:09,950 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:09,953 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:10,017 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:10,577 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:11,130 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:11,679 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:12,236 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 09:49:12,239 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-12 10:32:55,316 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-12 10:40:08,768 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.103
2025-03-12 10:40:08,772 [application.py:log_request()] - 101 GET /websocket (192.168.1.103) [_TRUSTED_USER_] 6.79ms
2025-03-12 10:40:08,776 [websockets.py:open()] - Websocket Opened: ID: 548351757856, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-12 10:40:08,795 [websockets.py:_handle_identify()] - Websocket 548351757856 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-12 10:45:39,871 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.115
2025-03-12 10:45:39,876 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 7.71ms
2025-03-12 10:45:39,877 [websockets.py:open()] - Websocket Opened: ID: 548353446336, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-12 10:45:39,890 [websockets.py:_handle_identify()] - Websocket 548353446336 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-12 11:44:01,576 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.103
2025-03-12 11:49:01,577 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.115
2025-03-12 12:01:40,762 [websockets.py:on_close()] - Websocket Closed: ID: 548351757856 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.98
2025-03-12 12:16:10,363 [websockets.py:on_close()] - Websocket Closed: ID: 548353446336 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.41
2025-03-12 12:17:59,047 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.115
2025-03-12 12:17:59,050 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 5.88ms
2025-03-12 12:17:59,051 [websockets.py:open()] - Websocket Opened: ID: 548353498560, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-12 12:17:59,067 [websockets.py:_handle_identify()] - Websocket 548353498560 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-12 12:32:35,219 [application.py:prepare()] - Upload Request Received from 192.168.1.115
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarylB79uv8IN1fYqe1d
2025-03-12 12:32:37,258 [application.py:post()] - Processing Uploaded File: CFFFP_YACS.gcode
2025-03-12 12:32:37,822 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2025-03-12 12:32:37,981 [shell_command.py:_check_proc_success()] - Command (/home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/components/file_manager/metadata.py -p /home/om/printer_data/gcodes -f "CFFFP_YACS.gcode") successfully finished
2025-03-12 12:32:37,990 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.115) [_TRUSTED_USER_] 2773.46ms
2025-03-12 12:34:04,483 [job_state.py:_status_update()] - Job Started: CFFFP_YACS.gcode
2025-03-12 12:36:50,709 [websockets.py:on_close()] - Websocket Closed: ID: 548353498560 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 1.65
2025-03-12 13:34:01,606 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.115
2025-03-12 13:46:32,691 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.103
2025-03-12 13:46:32,694 [application.py:log_request()] - 101 GET /websocket (192.168.1.103) [_TRUSTED_USER_] 5.78ms
2025-03-12 13:46:32,695 [websockets.py:open()] - Websocket Opened: ID: 548353496016, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-12 13:46:32,713 [websockets.py:_handle_identify()] - Websocket 548353496016 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-12 14:02:08,246 [server.py:_handle_term_signal()] - Exiting with signal SIGTERM
2025-03-12 14:02:08,443 [websockets.py:on_close()] - Websocket Closed: ID: 548353265472 Close Code: 1000, Close Reason: None, Pong Time Elapsed: 1.62
2025-03-12 14:02:08,467 [websockets.py:on_close()] - Websocket Closed: ID: 548353496016 Close Code: 1001, Close Reason: Server Shutdown, Pong Time Elapsed: 5.73
2025-03-12 14:02:08,476 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2025-03-12 14:02:08,500 [database.py:close()] - Database statistics:

announcements:
psize: 4096
depth: 0
branch_pages: 0
leaf_pages: 0
overflow_pages: 0
entries: 0
authorized_users:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
gcode_metadata:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 7
overflow_pages: 0
entries: 48
history:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 32
overflow_pages: 0
entries: 182
mainsail:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 9
maintenance:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
moonraker:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 7
update_manager:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 8
entries: 7
webcams:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
2025-03-12 14:02:08,540 [server.py:main()] - Server Shutdown
-------------------- Log Start | Wed Mar 12 08:32:11 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2025-03-12 14:02:11,324 [confighelper.py:read_file()] - Configuration File '/home/om/printer_data/config/moonraker.conf' parsed, total size: 2375 B
2025-03-12 14:02:11,326 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################
2025-03-12 14:02:11,597 [server.py:load_component()] - Component (secrets) loaded
2025-03-12 14:02:11,614 [server.py:load_component()] - Component (template) loaded
2025-03-12 14:02:11,632 [server.py:load_component()] - Component (klippy_connection) loaded
2025-03-12 14:02:12,623 [server.py:load_component()] - Component (application) loaded
2025-03-12 14:02:12,688 [server.py:load_component()] - Component (websockets) loaded
2025-03-12 14:02:12,833 [server.py:load_component()] - Component (dbus_manager) loaded
2025-03-12 14:02:12,866 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 182
2025-03-12 14:02:12,878 [server.py:load_component()] - Component (database) loaded
2025-03-12 14:02:12,933 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-03-12 14:02:12,991 [server.py:load_component()] - Component (file_manager) loaded
2025-03-12 14:02:13,004 [server.py:load_component()] - Component (klippy_apis) loaded
2025-03-12 14:02:13,590 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: add5f1c6
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.4
  total_memory: 880328
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73685
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-03-12 14:02:13,606 [server.py:load_component()] - Component (shell_command) loaded
2025-03-12 14:02:13,607 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-03-12 14:02:13,620 [server.py:load_component()] - Component (machine) loaded
2025-03-12 14:02:13,626 [server.py:load_component()] - Component (data_store) loaded
2025-03-12 14:02:13,634 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2025-03-12 14:02:13,636 [server.py:load_component()] - Component (proc_stats) loaded
2025-03-12 14:02:13,642 [server.py:load_component()] - Component (job_state) loaded
2025-03-12 14:02:13,654 [server.py:load_component()] - Component (job_queue) loaded
2025-03-12 14:02:13,672 [server.py:load_component()] - Component (http_client) loaded
2025-03-12 14:02:13,685 [server.py:load_component()] - Component (announcements) loaded
2025-03-12 14:02:13,694 [server.py:load_component()] - Component (webcam) loaded
2025-03-12 14:02:13,701 [server.py:load_component()] - Component (extensions) loaded
2025-03-12 14:02:13,765 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2025-03-12 14:02:13,776 [server.py:load_component()] - Component (authorization) loaded
2025-03-12 14:02:13,795 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-03-12 14:02:13,907 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/om/moonraker-env
2025-03-12 14:02:13,917 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/om/klippy-env
2025-03-12 14:02:13,944 [server.py:load_component()] - Component (update_manager) loaded
2025-03-12 14:02:13,954 [server.py:load_component()] - Component (history) loaded
2025-03-12 14:02:13,957 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-03-12 14:02:13,998 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-03-12 14:02:14,086 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-03-12 14:02:14,087 [machine.py:validation_init()] - Installation version in database up to date
2025-03-12 14:02:15,571 [machine.py:check_virt_status()] - No Virtualization Detected
2025-03-12 14:02:15,594 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.117
2025-03-12 14:02:15,600 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.117
2025-03-12 14:02:15,710 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'network-online.target', 'sysinit.target']
**After=['systemd-journald.socket', 'system.slice', 'network-online.target', 'sysinit.target', 'klipper.service', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om
2025-03-12 14:02:15,710 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-03-12 14:02:15,711 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-03-12 14:02:15,713 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-03-12 14:02:15,713 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.117
2025-03-12 14:02:15,714 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-03-12 14:02:15,715 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['-.mount', 'klipper-mcu.service', 'network-online.target', 'basic.target', 'system.slice', 'systemd-journald.socket', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-12 14:02:15,716 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-03-12 14:02:15,716 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2025-03-12 14:02:15,717 [update_manager.py:component_init()] - Removing stale update_manager data: crowsnest
2025-03-12 14:02:15,725 [update_manager.py:component_init()] - Removing stale update_manager data: mainsail
2025-03-12 14:02:15,733 [update_manager.py:component_init()] - Removing stale update_manager data: mainsail-config
2025-03-12 14:02:15,739 [update_manager.py:component_init()] - Removing stale update_manager data: sonar
2025-03-12 14:02:15,748 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-03-12 14:02:15,842 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2025-03-12 14:02:16,967 [confighelper.py:create_backup()] - Backing up last working configuration to '/home/om/printer_data/config/.moonraker.conf.bkp'
2025-03-12 14:02:16,976 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/om/printer_data/comms/moonraker.sock'
2025-03-12 14:02:16,988 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: Go3D
2025-03-12 14:02:16,990 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-03-12 14:02:17,246 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-12 14:02:17,403 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-12 14:02:17,446 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 4.62ms
2025-03-12 14:02:17,447 [websockets.py:open()] - Websocket Opened: ID: 547634962336, Proxied: False, User Agent: , Host Name: 127.0.0.1
2025-03-12 14:02:17,683 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396a-dirty
2025-03-12 14:02:17,722 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-12 14:02:17,725 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-12 14:02:17,767 [websockets.py:_handle_identify()] - Websocket 547634962336 Client Identified - Name: KlipperScreen, Version: v0.4.5-10-43ad9fc6-dirty, Type: display
2025-03-12 14:02:17,973 [job_state.py:_handle_started()] - Job state initialized: paused
2025-03-12 14:02:18,262 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-12 14:02:18,735 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-12 14:02:21,663 [base_deploy.py:log_info()] - PackageKit: Detected 152 package updates:
avahi-daemon
base-files
bind9-host
bind9-libs
bluez
bsdextrautils
bsdutils
busybox
cifs-utils
curl
distro-info-data
dns-root-data
dnsmasq-base
e2fsprogs
eject
exfatprogs
fdisk
ffmpeg
ghostscript
git-man
gtk-update-icon-cache
less
libaom0
libarchive13
libavahi-client3
libavahi-common-data
libavahi-common3
libavahi-core7
libavcodec-dev
libavcodec58
libavdevice58
libavfilter7
libavformat-dev
libavformat58
libavresample4
libavutil-dev
libavutil56
libbluetooth3
libc-bin
libc-dev-bin
libc-devtools
libc-l10n
libc6
libc6-dbg
libc6-dev
libcom-err2
libcups2
libcurl3-gnutls
libcurl4
libdav1d4
libde265-0
libebml5
libexpat1
libexpat1-dev
libext2fs2
libfdisk1
libgdk-pixbuf-2.0-0
libgdk-pixbuf2.0-bin
libgdk-pixbuf2.0-common
libglib2.0-0
libglib2.0-bin
libglib2.0-data
libglib2.0-dev
libglib2.0-dev-bin
libgnutls30
libgs9
libgs9-common
libgssapi-krb5-2
libgstreamer-plugins-base1.0-0
libgstreamer1.0-0
libgtk-3-0
libgtk-3-bin
libgtk-3-common
libheif1
libjs-jquery-ui
libk5crypto3
libkrb5-3
libkrb5support0
libmariadb3
libminizip1
libmpg123-0
libndp0
libnftables1
libnghttp2-14
libnss3
libntfs-3g883
libpam-systemd
libperl5.32
libpostproc55
libpq5
libpython3.9
libpython3.9-dev
libpython3.9-minimal
libpython3.9-stdlib
libsmartcols1
libsoup-gnome2.4-1
libsoup2.4-1
libsqlite3-0
libss2
libssh2-1
libssl-dev
libssl1.1
libswresample-dev
libswresample3
libswscale5
libsystemd0
libtasn1-6
libtiff5
libudev1
libuv1
libvpx6
libxerces-c3.2
libxml2
libzmq5
locales
logsave
mariadb-common
mount
nano
net-tools
nfs-common
nftables
ntfs-3g
openssh-client
openssh-server
openssh-sftp-server
openssl
perl
perl-base
perl-modules-5.32
python3-idna
python3-pil
python3-pkg-resources
python3-setuptools
python3-urllib3
python3.9
python3.9-dev
python3.9-minimal
python3.9-venv
rfkill
rsync
ssh
systemd
systemd-sysv
systemd-timesyncd
tar
tzdata
ucf
udev
util-linux
wpasupplicant
xserver-xorg-core
2025-03-12 14:02:21,748 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker status --porcelain -b) successfully finished
2025-03-12 14:02:21,813 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker branch --list --no-color) successfully finished
2025-03-12 14:02:21,862 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker remote get-url origin) successfully finished
2025-03-12 14:02:23,959 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker fetch origin --prune --progress) successfully finished
2025-03-12 14:02:24,001 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker merge-base --is-ancestor HEAD origin/master) successfully finished
2025-03-12 14:02:24,040 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker rev-parse HEAD) successfully finished
2025-03-12 14:02:24,087 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker describe --always --tags --long --dirty --abbrev=8) successfully finished
2025-03-12 14:02:24,113 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker rev-parse origin/master) successfully finished
2025-03-12 14:02:24,146 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker describe origin/master --always --tags --long --abbrev=8) successfully finished
2025-03-12 14:02:24,185 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker rev-list HEAD..4eb23ef2817dc56e9a8a2bf81e1a011ee27888e3 --count) successfully finished
2025-03-12 14:02:24,228 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker log a23187b4afa632da8a90cb9eae83f0f6a5eec903..origin/master --format="sha:%H%x1Dauthor:%an%x1Ddate:%ct%x1Dsubject:%s%x1Dmessage:%b%x1E" --max-count=100) successfully finished
2025-03-12 14:02:24,366 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/moonraker for-each-ref --count=100 --sort='-creatordate' --contains=HEAD --merged=origin/master --format='%(if)%(*objecttype)%(then)%(*objecttype) %(*objectname)%(else)%(objecttype) %(objectname)%(end) %(refname)' 'refs/tags') successfully finished
2025-03-12 14:02:24,368 [git_deploy.py:log_repo_info()] - Git Repo moonraker Detected:
Owner: Arksine
Repository Name: moonraker
Path: /home/om/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Recovery URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Upstream Commit SHA: 4eb23ef2817dc56e9a8a2bf81e1a011ee27888e3
Current Version: v0.8.0-268-ga23187b4
Upstream Version: v0.9.3-67-g4eb23ef2
Rollback Commit: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Rollback Branch: master
Rollback Version: v0.8.0-268-ga23187b4
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 220
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
2025-03-12 14:02:24,369 [base_deploy.py:log_info()] - Git Repo moonraker: Channel: dev
2025-03-12 14:02:24,369 [base_deploy.py:log_info()] - Git Repo moonraker: Validity check for git repo passed
2025-03-12 14:02:24,646 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper status --porcelain -b) successfully finished
2025-03-12 14:02:24,697 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper branch --list --no-color) successfully finished
2025-03-12 14:02:24,746 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper remote get-url origin) successfully finished
2025-03-12 14:02:44,022 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper fetch origin --prune --progress) successfully finished
2025-03-12 14:02:44,081 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper merge-base --is-ancestor HEAD origin/master) successfully finished
2025-03-12 14:02:44,134 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper rev-parse HEAD) successfully finished
2025-03-12 14:02:44,403 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper describe --always --tags --long --dirty --abbrev=8) successfully finished
2025-03-12 14:02:44,430 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper rev-parse origin/master) successfully finished
2025-03-12 14:02:44,673 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper describe origin/master --always --tags --long --abbrev=8) successfully finished
2025-03-12 14:02:44,716 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper rev-list HEAD..47aa28e5300d75764add52e34b23b1804147626c --count) successfully finished
2025-03-12 14:02:44,768 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper log d785b396a72b57c073ce5bdf7a9d5e9fe39fc914..origin/master --format="sha:%H%x1Dauthor:%an%x1Ddate:%ct%x1Dsubject:%s%x1Dmessage:%b%x1E" --max-count=100) successfully finished
2025-03-12 14:02:45,013 [shell_command.py:_check_proc_success()] - Command (git -C /home/om/klipper for-each-ref --count=100 --sort='-creatordate' --contains=HEAD --merged=origin/master --format='%(if)%(*objecttype)%(then)%(*objecttype) %(*objectname)%(else)%(objecttype) %(objectname)%(end) %(refname)' 'refs/tags') successfully finished
2025-03-12 14:02:45,015 [git_deploy.py:log_repo_info()] - Git Repo klipper Detected:
Owner: Klipper3d
Repository Name: klipper
Path: /home/om/klipper
Remote: origin
Branch: master
Remote URL: https://github.com/Klipper3d/klipper.git
Recovery URL: https://github.com/Klipper3d/klipper.git
Current Commit SHA: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Upstream Commit SHA: 47aa28e5300d75764add52e34b23b1804147626c
Current Version: v0.12.0-85-gd785b396
Upstream Version: v0.12.0-457-g47aa28e5
Rollback Commit: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Rollback Branch: master
Rollback Version: v0.12.0-85-gd785b396
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 372
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']
2025-03-12 14:02:45,016 [base_deploy.py:log_info()] - Git Repo klipper: Channel: dev
2025-03-12 14:02:45,017 [base_deploy.py:log_info()] - Git Repo klipper: Validity check for git repo passed
2025-03-12 14:02:45,018 [git_deploy.py:_check_repo_status()] - Git Repo klipper-backup: path '/home/om/klipper-backup' is not a valid git repo
2025-03-12 14:02:45,018 [git_deploy.py:refresh_repo_state()] - Git Repo klipper-backup: Initialization failure
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 365, in refresh_repo_state
    self._verify_repo()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 776, in _verify_repo
    raise self.server.error(
moonraker.utils.ServerError: Git Repo klipper-backup: repo not initialized
2025-03-12 14:02:45,019 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 57, in refresh
    await self._update_repo_state()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 63, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 365, in refresh_repo_state
    self._verify_repo()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 776, in _verify_repo
    raise self.server.error(
moonraker.utils.ServerError: Git Repo klipper-backup: repo not initialized
2025-03-12 14:03:57,629 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.103
2025-03-12 14:03:57,633 [application.py:log_request()] - 101 GET /websocket (192.168.1.103) [_TRUSTED_USER_] 6.70ms
2025-03-12 14:03:57,634 [websockets.py:open()] - Websocket Opened: ID: 547331220480, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-12 14:03:57,652 [websockets.py:_handle_identify()] - Websocket 547331220480 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-12 15:07:15,733 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-03-12 15:07:15,734 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.103
2025-03-12 15:13:35,673 [websockets.py:on_close()] - Websocket Closed: ID: 547331220480 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 8.03
2025-03-12 15:13:35,863 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.103
2025-03-12 15:13:35,868 [application.py:log_request()] - 101 GET /websocket (192.168.1.103) [_TRUSTED_USER_] 8.99ms
2025-03-12 15:13:35,870 [websockets.py:open()] - Websocket Opened: ID: 547331221872, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-12 15:13:35,900 [websockets.py:_handle_identify()] - Websocket 547331221872 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-12 15:14:04,391 [application.py:prepare()] - Upload Request Received from 192.168.1.103
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryXc3V9dtN1FEGEeNQ
2025-03-12 15:14:04,423 [application.py:post()] - Processing Uploaded File: log-backup.cfg
2025-03-12 15:14:04,449 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.103) [_TRUSTED_USER_] 69.85ms
2025-03-12 15:15:51,487 [application.py:prepare()] - Upload Request Received from 192.168.1.103
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryg5qyWA0iZBHDRjcq
2025-03-12 15:15:51,514 [application.py:post()] - Processing Uploaded File: log-backup.cfg
2025-03-12 15:15:51,529 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.103) [_TRUSTED_USER_] 44.18ms
2025-03-12 15:16:08,406 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-12 15:16:08,865 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-12 15:20:15,802 [application.py:prepare()] - Upload Request Received from 192.168.1.103
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDBua3P7enhFWnuTl
2025-03-12 15:20:15,867 [application.py:post()] - Processing Uploaded File: printer.cfg
2025-03-12 15:20:15,881 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.103) [_TRUSTED_USER_] 81.07ms
2025-03-12 15:20:25,338 [application.py:prepare()] - Upload Request Received from 192.168.1.103
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryZv13glUOxl1YBR4F
2025-03-12 15:20:25,382 [application.py:post()] - Processing Uploaded File: printer.cfg
2025-03-12 15:20:25,396 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.103) [_TRUSTED_USER_] 59.86ms
2025-03-12 15:20:26,592 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2025-03-12 15:20:28,612 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-12 15:20:28,730 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice', '-.mount']
**After=['-.mount', 'systemd-journald.socket', 'sysinit.target', 'klipper-mcu.service', 'system.slice', 'basic.target', 'network-online.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-12 15:20:31,661 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-12 15:20:31,664 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-12 15:20:31,723 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-12 15:20:31,898 [job_state.py:_handle_started()] - Job state initialized: standby
2025-03-12 15:20:32,178 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-12 15:20:32,666 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-12 15:40:30,675 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.115
2025-03-12 15:40:30,678 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 6.05ms
2025-03-12 15:40:30,679 [websockets.py:open()] - Websocket Opened: ID: 547321885984, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-12 15:40:30,718 [websockets.py:_handle_identify()] - Websocket 547321885984 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-12 15:40:47,508 [application.py:prepare()] - Upload Request Received from 192.168.1.115
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDfIYY2fKdePuknDF
2025-03-12 15:40:51,960 [application.py:post()] - Processing Uploaded File: 2x-alu_motherboardmountoctopuspro.gcode
2025-03-12 15:40:53,040 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2025-03-12 15:40:53,268 [shell_command.py:_check_proc_success()] - Command (/home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/components/file_manager/metadata.py -p /home/om/printer_data/gcodes -f "2x-alu_motherboardmountoctopuspro.gcode") successfully finished
2025-03-12 15:40:53,280 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.115) [_TRUSTED_USER_] 5776.87ms
2025-03-12 15:48:57,660 [application.py:prepare()] - Upload Request Received from 192.168.1.103
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarywfKeDqtcCkeL9PBT
2025-03-12 15:48:57,701 [application.py:post()] - Processing Uploaded File: log-backup.cfg
2025-03-12 15:48:57,726 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.103) [_TRUSTED_USER_] 68.62ms
2025-03-12 15:51:14,526 [machine.py:_find_public_ip()] - Failed to detect local IP address
2025-03-12 15:51:14,528 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://127.0.0.1
2025-03-12 15:51:40,790 [websockets.py:write_to_socket()] - Websocket closed while writing: 547321885984
2025-03-12 15:51:45,682 [websockets.py:on_close()] - Websocket Closed: ID: 547321885984 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.97
2025-03-12 15:51:46,056 [websockets.py:write_to_socket()] - Websocket closed while writing: 547331221872
2025-03-12 15:51:50,874 [websockets.py:on_close()] - Websocket Closed: ID: 547331221872 Close Code: None, Close Reason: None, Pong Time Elapsed: 45.00
2025-03-12 16:02:17,786 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-03-12 16:02:19,815 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-03-12 16:02:21,843 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [Errno -3] Temporary failure in name resolution
2025-03-12 16:22:15,768 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-03-12 16:32:07,716 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.117
2025-03-12 16:32:07,719 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.117
2025-03-12 16:42:15,772 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.115
2025-03-12 16:52:15,776 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.103
2025-03-12 17:16:47,898 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.103
2025-03-12 17:16:47,902 [application.py:log_request()] - 101 GET /websocket (192.168.1.103) [_TRUSTED_USER_] 6.65ms
2025-03-12 17:16:47,903 [websockets.py:open()] - Websocket Opened: ID: 547321641904, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-12 17:16:47,945 [websockets.py:_handle_identify()] - Websocket 547321641904 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-12 17:30:14,718 [machine.py:_parse_network_interfaces()] - Error processing network update
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/machine.py", line 630, in _parse_network_interfaces
    resp = await self.addr_cmd.run_with_response(log_complete=False)
  File "/home/om/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'ip -json -det address'
2025-03-12 18:01:37,945 [websockets.py:write_to_socket()] - Websocket closed while writing: 547321641904
2025-03-12 18:01:42,907 [websockets.py:on_close()] - Websocket Closed: ID: 547321641904 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.99
