-------------------- Log Start | Wed Mar 12 19:00:19 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################

Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 182

System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: add5f1c6
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.4
  total_memory: 880328
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73685
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'network-online.target', 'sysinit.target']
**After=['systemd-journald.socket', 'system.slice', 'network-online.target', 'sysinit.target', 'klipper.service', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice', '-.mount']
**After=['-.mount', 'systemd-journald.socket', 'sysinit.target', 'klipper-mcu.service', 'system.slice', 'basic.target', 'network-online.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
Git Repo moonraker: Warnings detected:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
Git Repo klipper: Warnings detected:
  Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']
Klipper Version: v0.12.0-85-gd785b396a-dirty
2025-03-13 00:30:19,319 [machine.py:_parse_network_interfaces()] - Error processing network update
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/machine.py", line 630, in _parse_network_interfaces
    resp = await self.addr_cmd.run_with_response(log_complete=False)
  File "/home/om/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'ip -json -det address'
2025-03-13 02:02:15,880 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:16,454 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:17,025 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:17,586 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:18,138 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:18,144 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:18,207 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:18,768 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:19,320 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:19,883 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:20,436 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:20,439 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:20,491 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:21,042 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:21,601 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:22,160 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:22,716 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:02:22,720 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:15,850 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:16,426 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:17,012 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:17,567 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:18,138 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:18,143 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:18,192 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:18,762 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:19,313 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:19,885 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:20,435 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:20,438 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:20,509 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:21,069 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:21,636 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:22,194 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:22,774 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 02:32:22,779 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:15,856 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:16,423 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:16,970 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:17,525 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:18,071 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:18,074 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:18,124 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:18,671 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:19,218 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:19,776 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:20,325 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:20,328 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:20,377 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:20,934 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:21,508 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:22,085 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:22,653 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:02:22,656 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:15,881 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:16,443 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:17,007 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:17,556 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:18,113 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:18,117 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:18,166 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:18,724 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:19,311 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:19,862 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:20,415 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:20,418 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:20,467 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:21,024 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:21,621 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:22,196 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:22,754 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 03:32:22,757 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:15,858 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:16,420 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:16,996 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:17,573 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:18,125 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:18,128 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:18,178 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:18,734 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:19,290 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:19,846 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:20,400 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:20,403 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:20,452 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:21,002 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:21,556 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:22,104 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:22,685 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:02:22,691 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:15,874 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:16,428 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:16,977 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:17,524 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:18,080 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:18,083 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:18,140 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:18,688 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:19,244 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:19,797 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:20,350 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:20,353 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:20,403 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:20,960 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:21,551 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:22,100 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:22,653 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 04:32:22,656 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:15,861 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:16,443 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:17,026 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:17,577 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:18,129 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:18,132 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:18,181 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:18,734 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:19,287 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:19,841 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:20,394 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:20,397 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:20,444 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:20,998 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:21,545 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:22,139 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:22,698 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:02:22,701 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:15,861 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:16,416 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:16,967 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:17,526 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:18,076 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:18,081 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:18,137 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:18,685 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:19,234 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:19,804 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:20,375 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:20,378 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:20,426 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:20,982 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:21,532 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:22,109 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:22,663 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 05:32:22,667 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:15,913 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:16,461 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:17,015 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:17,601 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:18,181 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:18,186 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:18,249 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:18,805 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:19,366 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:19,922 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:20,472 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:20,475 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:20,522 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:21,074 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:21,624 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:22,218 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:22,773 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:02:22,776 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:15,864 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:16,414 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:16,972 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:17,563 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:18,114 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:18,117 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:18,164 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:18,723 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:19,281 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:19,837 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:20,387 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:20,391 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:20,444 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:20,997 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:21,563 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:22,115 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:22,695 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 06:32:22,700 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:15,861 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:16,415 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:16,967 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:17,525 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:18,074 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:18,077 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:18,130 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:18,708 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:19,270 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:19,845 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:20,406 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:20,408 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:20,453 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:21,008 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:21,557 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:22,110 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:22,672 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:02:22,676 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:15,887 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:16,439 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:16,994 [iostream.py:_do_ssl_handshake()] - SSL Error on 17 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:17,542 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:18,092 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:18,094 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:18,145 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:18,692 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:19,255 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:19,804 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:20,358 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:20,360 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:20,413 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:20,993 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:21,578 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:22,129 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:22,684 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 07:32:22,687 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:15,868 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:16,423 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:16,975 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:17,560 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:18,123 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:18,126 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:18,173 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:18,724 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:19,275 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:19,830 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:20,386 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:20,389 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:20,440 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:20,992 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:21,544 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:22,096 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:22,677 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:02:22,681 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:15,864 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:16,414 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:16,964 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:17,528 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:18,083 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:18,085 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:18,138 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:18,690 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:19,250 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:19,806 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:20,366 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:20,368 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:20,441 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:20,991 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.110.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:21,546 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.111.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:22,099 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.108.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:22,652 [iostream.py:_do_ssl_handshake()] - SSL Error on 16 ('185.199.109.153', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 08:32:22,655 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'mainsail': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2025-03-13 09:44:17,396 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-13 09:44:34,851 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-13 10:06:29,120 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.115
2025-03-13 10:06:29,129 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 11.79ms
2025-03-13 10:06:29,130 [websockets.py:open()] - Websocket Opened: ID: 547321640224, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-13 10:06:29,206 [websockets.py:_handle_identify()] - Websocket 547321640224 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 10:15:39,970 [application.py:prepare()] - Upload Request Received from 192.168.1.115
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary39hvnjN8M1VJhwtl
2025-03-13 10:15:48,184 [application.py:post()] - Processing Uploaded File: 123.gcode
2025-03-13 10:15:49,072 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is disabled

2025-03-13 10:15:49,301 [shell_command.py:_check_proc_success()] - Command (/home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/components/file_manager/metadata.py -p /home/om/printer_data/gcodes -f "123.gcode") successfully finished
2025-03-13 10:15:49,313 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.115) [_TRUSTED_USER_] 9346.84ms
2025-03-13 10:19:37,545 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.118
2025-03-13 10:19:37,549 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.52ms
2025-03-13 10:19:37,550 [websockets.py:open()] - Websocket Opened: ID: 547321966800, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 10:19:37,565 [websockets.py:_handle_identify()] - Websocket 547321966800 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 10:19:47,990 [websockets.py:on_close()] - Websocket Closed: ID: 547321966800 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 0.43
2025-03-13 10:19:48,518 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.44ms
2025-03-13 10:19:48,519 [websockets.py:open()] - Websocket Opened: ID: 547321976528, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 10:19:48,562 [websockets.py:_handle_identify()] - Websocket 547321976528 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 10:20:08,608 [websockets.py:on_close()] - Websocket Closed: ID: 547321976528 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 0.08
2025-03-13 10:20:08,979 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.20ms
2025-03-13 10:20:08,980 [websockets.py:open()] - Websocket Opened: ID: 547321977008, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 10:20:09,031 [websockets.py:_handle_identify()] - Websocket 547321977008 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 10:23:07,178 [websockets.py:on_close()] - Websocket Closed: ID: 547321977008 Close Code: None, Close Reason: None, Pong Time Elapsed: 8.10
2025-03-13 10:24:13,357 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.66ms
2025-03-13 10:24:13,358 [websockets.py:open()] - Websocket Opened: ID: 547321978736, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 10:24:13,375 [websockets.py:_handle_identify()] - Websocket 547321978736 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 10:25:10,451 [websockets.py:on_close()] - Websocket Closed: ID: 547321978736 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 7.04
2025-03-13 10:25:15,197 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.07ms
2025-03-13 10:25:15,198 [websockets.py:open()] - Websocket Opened: ID: 547321977008, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 10:25:15,263 [websockets.py:_handle_identify()] - Websocket 547321977008 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 10:25:22,024 [job_state.py:_status_update()] - Job Started: 123.gcode
2025-03-13 10:31:13,963 [websockets.py:on_close()] - Websocket Closed: ID: 547321640224 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.82
2025-03-13 10:32:15,306 [websockets.py:on_close()] - Websocket Closed: ID: 547321977008 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 10.10
2025-03-13 10:52:16,065 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-03-13 10:56:51,083 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.14ms
2025-03-13 10:56:51,084 [websockets.py:open()] - Websocket Opened: ID: 547321978736, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 10:56:51,203 [websockets.py:_handle_identify()] - Websocket 547321978736 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:00:58,740 [websockets.py:on_close()] - Websocket Closed: ID: 547321978736 Close Code: None, Close Reason: None, Pong Time Elapsed: 7.50
2025-03-13 11:06:09,659 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.52ms
2025-03-13 11:06:09,660 [websockets.py:open()] - Websocket Opened: ID: 547311977136, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:06:09,678 [websockets.py:_handle_identify()] - Websocket 547311977136 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:06:29,790 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 5.21ms
2025-03-13 11:06:29,791 [websockets.py:open()] - Websocket Opened: ID: 547330955008, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:06:30,323 [websockets.py:_handle_identify()] - Websocket 547330955008 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:06:39,293 [websockets.py:on_close()] - Websocket Closed: ID: 547311977136 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 9.63
2025-03-13 11:06:39,784 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 7.36ms
2025-03-13 11:06:39,785 [websockets.py:open()] - Websocket Opened: ID: 547330956976, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:06:39,867 [websockets.py:_handle_identify()] - Websocket 547330956976 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:08:55,496 [websockets.py:on_close()] - Websocket Closed: ID: 547330956976 Close Code: None, Close Reason: None, Pong Time Elapsed: 5.50
2025-03-13 11:14:37,920 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.103
2025-03-13 11:14:37,928 [application.py:log_request()] - 101 GET /websocket (192.168.1.103) [_TRUSTED_USER_] 11.12ms
2025-03-13 11:14:37,929 [websockets.py:open()] - Websocket Opened: ID: 547330955872, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:14:37,943 [websockets.py:_handle_identify()] - Websocket 547330955872 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:20:29,806 [websockets.py:write_to_socket()] - Websocket closed while writing: 547330955008
2025-03-13 11:20:34,803 [websockets.py:on_close()] - Websocket Closed: ID: 547330955008 Close Code: None, Close Reason: None, Pong Time Elapsed: 39.11
2025-03-13 11:20:41,767 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 5.66ms
2025-03-13 11:20:41,769 [websockets.py:open()] - Websocket Opened: ID: 547321975376, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:20:41,793 [websockets.py:_handle_identify()] - Websocket 547321975376 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:22:01,868 [websockets.py:write_to_socket()] - Websocket closed while writing: 547321975376
2025-03-13 11:22:06,773 [websockets.py:on_close()] - Websocket Closed: ID: 547321975376 Close Code: None, Close Reason: None, Pong Time Elapsed: 43.38
2025-03-13 11:22:26,496 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 9.99ms
2025-03-13 11:22:26,499 [websockets.py:open()] - Websocket Opened: ID: 547330956400, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:22:26,535 [websockets.py:_handle_identify()] - Websocket 547330956400 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:22:34,813 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 6.37ms
2025-03-13 11:22:34,814 [websockets.py:open()] - Websocket Opened: ID: 547311978768, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:22:34,834 [websockets.py:_handle_identify()] - Websocket 547311978768 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:24:16,840 [websockets.py:on_close()] - Websocket Closed: ID: 547311978768 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.85
2025-03-13 11:30:46,718 [websockets.py:write_to_socket()] - Websocket closed while writing: 547330956400
2025-03-13 11:30:51,502 [websockets.py:on_close()] - Websocket Closed: ID: 547330956400 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.97
2025-03-13 11:35:55,461 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.54ms
2025-03-13 11:35:55,462 [websockets.py:open()] - Websocket Opened: ID: 547311979824, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:35:55,516 [websockets.py:_handle_identify()] - Websocket 547311979824 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:37:45,655 [websockets.py:write_to_socket()] - Websocket closed while writing: 547311979824
2025-03-13 11:37:50,467 [websockets.py:on_close()] - Websocket Closed: ID: 547311979824 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.97
2025-03-13 11:40:10,671 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.52ms
2025-03-13 11:40:10,672 [websockets.py:open()] - Websocket Opened: ID: 547311979392, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:40:10,688 [websockets.py:_handle_identify()] - Websocket 547311979392 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:40:55,058 [websockets.py:on_close()] - Websocket Closed: ID: 547311979392 Close Code: None, Close Reason: None, Pong Time Elapsed: 2.63
2025-03-13 11:41:55,137 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 6.93ms
2025-03-13 11:41:55,138 [websockets.py:open()] - Websocket Opened: ID: 547311978912, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:41:55,611 [websockets.py:_handle_identify()] - Websocket 547311978912 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 11:47:18,833 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.17ms
2025-03-13 11:47:18,834 [websockets.py:open()] - Websocket Opened: ID: 547311978816, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:47:42,319 [websockets.py:on_close()] - Websocket Closed: ID: 547311978816 Close Code: None, Close Reason: None, Pong Time Elapsed: 23.49
2025-03-13 11:58:18,625 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.17ms
2025-03-13 11:58:18,626 [websockets.py:open()] - Websocket Opened: ID: 547311979200, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 11:58:18,638 [websockets.py:_handle_identify()] - Websocket 547311979200 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:06:35,645 [klippy_connection.py:wait()] - Request 'gcode/script' pending: 60.00 seconds
2025-03-13 12:06:39,298 [websockets.py:on_close()] - Websocket Closed: ID: 547311979200 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 0.51
2025-03-13 12:06:39,798 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.48ms
2025-03-13 12:06:39,799 [websockets.py:open()] - Websocket Opened: ID: 547321639792, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:06:39,855 [websockets.py:_handle_identify()] - Websocket 547321639792 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:07:28,740 [websockets.py:on_close()] - Websocket Closed: ID: 547321639792 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 8.93
2025-03-13 12:07:29,216 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.37ms
2025-03-13 12:07:29,216 [websockets.py:open()] - Websocket Opened: ID: 547321885216, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:07:29,265 [websockets.py:_handle_identify()] - Websocket 547321885216 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:08:45,632 [websockets.py:on_close()] - Websocket Closed: ID: 547311978912 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.34
2025-03-13 12:15:30,373 [websockets.py:on_close()] - Websocket Closed: ID: 547321885216 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.14
2025-03-13 12:16:45,137 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.36ms
2025-03-13 12:16:45,138 [websockets.py:open()] - Websocket Opened: ID: 547312081552, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:16:45,174 [websockets.py:_handle_identify()] - Websocket 547312081552 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:17:16,086 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.103
2025-03-13 12:18:44,773 [websockets.py:on_close()] - Websocket Closed: ID: 547312081552 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 9.62
2025-03-13 12:18:45,201 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.55ms
2025-03-13 12:18:45,202 [websockets.py:open()] - Websocket Opened: ID: 547321888720, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:18:45,292 [websockets.py:_handle_identify()] - Websocket 547321888720 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:24:06,300 [websockets.py:on_close()] - Websocket Closed: ID: 547321888720 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.06
2025-03-13 12:25:51,820 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.86ms
2025-03-13 12:25:51,822 [websockets.py:open()] - Websocket Opened: ID: 547321914272, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:25:52,207 [websockets.py:_handle_identify()] - Websocket 547321914272 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:31:31,841 [websockets.py:write_to_socket()] - Websocket closed while writing: 547321914272
2025-03-13 12:31:36,828 [websockets.py:on_close()] - Websocket Closed: ID: 547321914272 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.83
2025-03-13 12:35:34,485 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.74ms
2025-03-13 12:35:34,487 [websockets.py:open()] - Websocket Opened: ID: 547331362528, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:35:34,504 [websockets.py:_handle_identify()] - Websocket 547331362528 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:37:05,996 [websockets.py:on_close()] - Websocket Closed: ID: 547331362528 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 1.41
2025-03-13 12:37:06,519 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.29ms
2025-03-13 12:37:06,520 [websockets.py:open()] - Websocket Opened: ID: 547331359168, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:37:06,564 [websockets.py:_handle_identify()] - Websocket 547331359168 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:42:16,093 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.115
2025-03-13 12:44:46,868 [websockets.py:write_to_socket()] - Websocket closed while writing: 547331359168
2025-03-13 12:44:51,529 [websockets.py:on_close()] - Websocket Closed: ID: 547331359168 Close Code: None, Close Reason: None, Pong Time Elapsed: 45.00
2025-03-13 12:45:50,483 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 7.20ms
2025-03-13 12:45:50,485 [websockets.py:open()] - Websocket Opened: ID: 547634416896, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:45:50,498 [websockets.py:_handle_identify()] - Websocket 547634416896 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:46:54,769 [websockets.py:on_close()] - Websocket Closed: ID: 547634416896 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 4.02
2025-03-13 12:46:55,286 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.57ms
2025-03-13 12:46:55,288 [websockets.py:open()] - Websocket Opened: ID: 547321440912, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:46:55,343 [websockets.py:_handle_identify()] - Websocket 547321440912 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:48:46,664 [websockets.py:on_close()] - Websocket Closed: ID: 547321440912 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.14
2025-03-13 12:49:53,799 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.38ms
2025-03-13 12:49:53,800 [websockets.py:open()] - Websocket Opened: ID: 547321913936, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:49:53,849 [websockets.py:_handle_identify()] - Websocket 547321913936 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:51:03,367 [websockets.py:on_close()] - Websocket Closed: ID: 547321913936 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 9.33
2025-03-13 12:51:03,946 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.87ms
2025-03-13 12:51:03,948 [websockets.py:open()] - Websocket Opened: ID: 547321915184, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:51:04,015 [websockets.py:_handle_identify()] - Websocket 547321915184 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:57:04,118 [websockets.py:write_to_socket()] - Websocket closed while writing: 547321915184
2025-03-13 12:57:08,951 [websockets.py:on_close()] - Websocket Closed: ID: 547321915184 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.98
2025-03-13 12:59:16,711 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.19ms
2025-03-13 12:59:16,712 [websockets.py:open()] - Websocket Opened: ID: 547321915904, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 12:59:16,786 [websockets.py:_handle_identify()] - Websocket 547321915904 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 12:59:21,343 [websockets.py:on_close()] - Websocket Closed: ID: 547330955872 Close Code: None, Close Reason: None, Pong Time Elapsed: 3.38
2025-03-13 13:01:17,655 [websockets.py:on_close()] - Websocket Closed: ID: 547321915904 Close Code: None, Close Reason: None, Pong Time Elapsed: 0.92
2025-03-13 13:02:23,351 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.80ms
2025-03-13 13:02:23,352 [websockets.py:open()] - Websocket Opened: ID: 547331361952, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 13:02:23,422 [websockets.py:_handle_identify()] - Websocket 547331361952 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 13:08:13,442 [websockets.py:write_to_socket()] - Websocket closed while writing: 547331361952
2025-03-13 13:08:18,359 [websockets.py:on_close()] - Websocket Closed: ID: 547331361952 Close Code: None, Close Reason: None, Pong Time Elapsed: 44.98
2025-03-13 13:12:26,782 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.23ms
2025-03-13 13:12:26,783 [websockets.py:open()] - Websocket Opened: ID: 547331360224, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 13:12:26,817 [websockets.py:_handle_identify()] - Websocket 547331360224 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 13:13:47,658 [websockets.py:on_close()] - Websocket Closed: ID: 547331360224 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 0.86
2025-03-13 13:13:48,188 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 5.45ms
2025-03-13 13:13:48,189 [websockets.py:open()] - Websocket Opened: ID: 547331362384, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 13:13:48,210 [websockets.py:_handle_identify()] - Websocket 547331362384 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 13:19:36,092 [websockets.py:on_close()] - Websocket Closed: ID: 547331362384 Close Code: None, Close Reason: None, Pong Time Elapsed: 7.66
2025-03-13 13:27:31,308 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.07ms
2025-03-13 13:27:31,309 [websockets.py:open()] - Websocket Opened: ID: 547331360464, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 13:27:31,352 [websockets.py:_handle_identify()] - Websocket 547331360464 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 13:32:08,406 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2025-03-13 13:32:13,657 [websockets.py:on_close()] - Websocket Closed: ID: 547331360464 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 2.33
2025-03-13 13:32:14,130 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 6.48ms
2025-03-13 13:32:14,131 [websockets.py:open()] - Websocket Opened: ID: 547331222688, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 13:32:14,249 [websockets.py:_handle_identify()] - Websocket 547331222688 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 13:32:29,360 [websockets.py:on_close()] - Websocket Closed: ID: 547331222688 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 5.22
2025-03-13 13:32:29,856 [application.py:log_request()] - 101 GET /websocket (192.168.1.118) [_TRUSTED_USER_] 4.89ms
2025-03-13 13:32:29,857 [websockets.py:open()] - Websocket Opened: ID: 547311977520, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.117
2025-03-13 13:32:29,867 [websockets.py:_handle_identify()] - Websocket 547311977520 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 13:32:31,642 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: server.files.metadata, Code: -32601, Message: Metadata not available for <123.gcode>
2025-03-13 13:32:33,548 [websockets.py:on_close()] - Websocket Closed: ID: 547311977520 Close Code: None, Close Reason: None, Pong Time Elapsed: 3.70
2025-03-13 13:32:34,374 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.103
2025-03-13 13:32:34,378 [application.py:log_request()] - 101 GET /websocket (192.168.1.103) [_TRUSTED_USER_] 5.69ms
2025-03-13 13:32:34,379 [websockets.py:open()] - Websocket Opened: ID: 547311979392, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-13 13:32:34,392 [websockets.py:_handle_identify()] - Websocket 547311979392 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 13:32:36,966 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: server.files.metadata, Code: -32601, Message: Metadata not available for <123.gcode>
2025-03-13 13:35:01,447 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.115
2025-03-13 13:35:01,451 [application.py:log_request()] - 101 GET /websocket (192.168.1.115) [_TRUSTED_USER_] 7.18ms
2025-03-13 13:35:01,452 [websockets.py:open()] - Websocket Opened: ID: 547634416080, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36, Host Name: 192.168.1.117
2025-03-13 13:35:07,513 [websockets.py:_handle_identify()] - Websocket 547634416080 Client Identified - Name: mainsail, Version: 2.12.0, Type: web
2025-03-13 13:35:09,101 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: server.files.metadata, Code: -32601, Message: Metadata not available for <123.gcode>
-------------------- Log Start | Thu Mar 13 08:14:19 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2025-03-13 13:44:19,445 [confighelper.py:read_file()] - Configuration File '/home/om/printer_data/config/moonraker.conf' parsed, total size: 2375 B
2025-03-13 13:44:19,446 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################
2025-03-13 13:44:20,071 [server.py:load_component()] - Component (secrets) loaded
2025-03-13 13:44:20,104 [server.py:load_component()] - Component (template) loaded
2025-03-13 13:44:20,128 [server.py:load_component()] - Component (klippy_connection) loaded
2025-03-13 13:44:22,996 [server.py:load_component()] - Component (application) loaded
2025-03-13 13:44:23,201 [server.py:load_component()] - Component (websockets) loaded
2025-03-13 13:44:23,838 [server.py:load_component()] - Component (dbus_manager) loaded
2025-03-13 13:44:24,208 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 183
2025-03-13 13:44:24,344 [server.py:load_component()] - Component (database) loaded
2025-03-13 13:44:24,605 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-03-13 13:44:24,862 [server.py:load_component()] - Component (file_manager) loaded
2025-03-13 13:44:24,896 [server.py:load_component()] - Component (klippy_apis) loaded
2025-03-13 13:44:25,934 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: add5f1c6
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.4
  total_memory: 880328
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73685
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-03-13 13:44:25,964 [server.py:load_component()] - Component (shell_command) loaded
2025-03-13 13:44:25,965 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-03-13 13:44:25,989 [server.py:load_component()] - Component (machine) loaded
2025-03-13 13:44:26,015 [server.py:load_component()] - Component (data_store) loaded
2025-03-13 13:44:26,051 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2025-03-13 13:44:26,054 [server.py:load_component()] - Component (proc_stats) loaded
2025-03-13 13:44:26,078 [server.py:load_component()] - Component (job_state) loaded
2025-03-13 13:44:26,097 [server.py:load_component()] - Component (job_queue) loaded
2025-03-13 13:44:26,187 [server.py:load_component()] - Component (http_client) loaded
2025-03-13 13:44:26,223 [server.py:load_component()] - Component (announcements) loaded
2025-03-13 13:44:26,251 [server.py:load_component()] - Component (webcam) loaded
2025-03-13 13:44:26,278 [server.py:load_component()] - Component (extensions) loaded
2025-03-13 13:44:26,307 [server.py:load_component()] - Component (history) loaded
2025-03-13 13:44:26,598 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/om/moonraker-env
2025-03-13 13:44:26,606 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/om/klippy-env
2025-03-13 13:44:26,629 [server.py:load_component()] - Component (update_manager) loaded
2025-03-13 13:44:27,170 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2025-03-13 13:44:27,183 [server.py:load_component()] - Component (authorization) loaded
2025-03-13 13:44:27,208 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-03-13 13:44:27,212 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-03-13 13:44:27,247 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-03-13 13:44:27,395 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-03-13 13:44:27,396 [machine.py:validation_init()] - Installation version in database up to date
2025-03-13 13:44:30,437 [machine.py:check_virt_status()] - No Virtualization Detected
2025-03-13 13:44:30,491 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.117
2025-03-13 13:44:30,507 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.117
2025-03-13 13:44:30,691 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target', 'network-online.target']
**After=['systemd-journald.socket', 'system.slice', 'klipper.service', 'sysinit.target', 'basic.target', 'network-online.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om
2025-03-13 13:44:30,692 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-03-13 13:44:30,693 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-03-13 13:44:30,699 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-03-13 13:44:30,700 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.117
2025-03-13 13:44:30,704 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-03-13 13:44:30,706 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice', '-.mount']
**After=['-.mount', 'systemd-journald.socket', 'sysinit.target', 'klipper-mcu.service', 'system.slice', 'basic.target', 'network-online.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-13 13:44:30,706 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-03-13 13:44:30,711 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2025-03-13 13:44:30,717 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-03-13 14:56:23,551 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2025-03-13 14:56:23,606 [git_deploy.py:log_repo_info()] - Git Repo moonraker Detected:
Owner: Arksine
Repository Name: moonraker
Path: /home/om/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Recovery URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Upstream Commit SHA: 4eb23ef2817dc56e9a8a2bf81e1a011ee27888e3
Current Version: v0.8.0-268-ga23187b4
Upstream Version: v0.9.3-67-g4eb23ef2
Rollback Commit: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Rollback Branch: master
Rollback Version: v0.8.0-268-ga23187b4
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 220
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
2025-03-13 14:56:23,660 [git_deploy.py:log_repo_info()] - Git Repo klipper Detected:
Owner: Klipper3d
Repository Name: klipper
Path: /home/om/klipper
Remote: origin
Branch: master
Remote URL: https://github.com/Klipper3d/klipper.git
Recovery URL: https://github.com/Klipper3d/klipper.git
Current Commit SHA: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Upstream Commit SHA: 47aa28e5300d75764add52e34b23b1804147626c
Current Version: v0.12.0-85-gd785b396
Upstream Version: v0.12.0-457-g47aa28e5
Rollback Commit: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Rollback Branch: master
Rollback Version: v0.12.0-85-gd785b396
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 372
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']
2025-03-13 14:56:23,667 [base_deploy.py:log_info()] - PackageKit: Next refresh in: 5 Days, 23 Hours, 5 Minutes, 58 Seconds
2025-03-13 14:56:23,668 [base_deploy.py:log_info()] - Git Repo moonraker: Next refresh in: 5 Days, 23 Hours, 6 Minutes, 1 Second
2025-03-13 14:56:23,668 [base_deploy.py:log_info()] - Git Repo klipper: Next refresh in: 5 Days, 23 Hours, 6 Minutes, 21 Seconds
2025-03-13 14:56:23,670 [git_deploy.py:_check_repo_status()] - Git Repo klipper-backup: path '/home/om/klipper-backup' is not a valid git repo
2025-03-13 14:56:23,671 [git_deploy.py:refresh_repo_state()] - Git Repo klipper-backup: Initialization failure
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 365, in refresh_repo_state
    self._verify_repo()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 776, in _verify_repo
    raise self.server.error(
moonraker.utils.ServerError: Git Repo klipper-backup: repo not initialized
2025-03-13 14:56:23,672 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 57, in refresh
    await self._update_repo_state()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 63, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 365, in refresh_repo_state
    self._verify_repo()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 776, in _verify_repo
    raise self.server.error(
moonraker.utils.ServerError: Git Repo klipper-backup: repo not initialized
2025-03-13 14:56:23,687 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/om/printer_data/comms/moonraker.sock'
2025-03-13 14:56:23,695 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: Go3D
2025-03-13 14:56:23,699 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-03-13 14:56:23,961 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-13 14:56:24,165 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', '-.mount', 'system.slice']
**After=['-.mount', 'basic.target', 'systemd-journald.socket', 'klipper-mcu.service', 'system.slice', 'network-online.target', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-13 14:56:24,423 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396a-dirty
2025-03-13 14:56:24,488 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-13 14:56:24,493 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-13 14:56:24,738 [job_state.py:_handle_started()] - Job state initialized: standby
2025-03-13 14:56:25,005 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-13 14:56:25,490 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-13 14:56:34,867 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-13 14:56:34,890 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 4.39ms
2025-03-13 14:56:34,891 [websockets.py:open()] - Websocket Opened: ID: 548353868320, Proxied: False, User Agent: , Host Name: 127.0.0.1
2025-03-13 14:56:34,981 [websockets.py:_handle_identify()] - Websocket 548353868320 Client Identified - Name: KlipperScreen, Version: v0.4.5-10-43ad9fc6-dirty, Type: display
2025-03-13 14:56:35,770 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
-------------------- Log Start | Thu Mar 13 09:28:15 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2025-03-13 14:58:15,318 [confighelper.py:read_file()] - Configuration File '/home/om/printer_data/config/moonraker.conf' parsed, total size: 2375 B
2025-03-13 14:58:15,319 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################
2025-03-13 14:58:15,747 [server.py:load_component()] - Component (secrets) loaded
2025-03-13 14:58:15,780 [server.py:load_component()] - Component (template) loaded
2025-03-13 14:58:15,799 [server.py:load_component()] - Component (klippy_connection) loaded
2025-03-13 14:58:18,374 [server.py:load_component()] - Component (application) loaded
2025-03-13 14:58:18,569 [server.py:load_component()] - Component (websockets) loaded
2025-03-13 14:58:19,003 [server.py:load_component()] - Component (dbus_manager) loaded
2025-03-13 14:58:19,189 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 184
2025-03-13 14:58:19,209 [server.py:load_component()] - Component (database) loaded
2025-03-13 14:58:19,295 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-03-13 14:58:19,472 [server.py:load_component()] - Component (file_manager) loaded
2025-03-13 14:58:19,490 [server.py:load_component()] - Component (klippy_apis) loaded
2025-03-13 14:58:20,525 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: add5f1c6
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.4
  total_memory: 880328
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73685
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-03-13 14:58:20,541 [server.py:load_component()] - Component (shell_command) loaded
2025-03-13 14:58:20,541 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-03-13 14:58:20,562 [server.py:load_component()] - Component (machine) loaded
2025-03-13 14:58:20,578 [server.py:load_component()] - Component (data_store) loaded
2025-03-13 14:58:20,589 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2025-03-13 14:58:20,592 [server.py:load_component()] - Component (proc_stats) loaded
2025-03-13 14:58:20,604 [server.py:load_component()] - Component (job_state) loaded
2025-03-13 14:58:20,634 [server.py:load_component()] - Component (job_queue) loaded
2025-03-13 14:58:20,668 [server.py:load_component()] - Component (http_client) loaded
2025-03-13 14:58:20,705 [server.py:load_component()] - Component (announcements) loaded
2025-03-13 14:58:20,741 [server.py:load_component()] - Component (webcam) loaded
2025-03-13 14:58:20,767 [server.py:load_component()] - Component (extensions) loaded
2025-03-13 14:58:20,795 [server.py:load_component()] - Component (history) loaded
2025-03-13 14:58:20,825 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-03-13 14:58:21,117 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/om/moonraker-env
2025-03-13 14:58:21,132 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/om/klippy-env
2025-03-13 14:58:21,152 [server.py:load_component()] - Component (update_manager) loaded
2025-03-13 14:58:21,293 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2025-03-13 14:58:21,310 [server.py:load_component()] - Component (authorization) loaded
2025-03-13 14:58:21,316 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-03-13 14:58:21,353 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-03-13 14:58:21,513 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-03-13 14:58:21,516 [machine.py:validation_init()] - Installation version in database up to date
2025-03-13 14:58:23,985 [machine.py:check_virt_status()] - No Virtualization Detected
2025-03-13 14:58:26,518 [machine.py:_parse_network_interfaces()] - Error processing network update
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/machine.py", line 630, in _parse_network_interfaces
    resp = await self.addr_cmd.run_with_response(log_complete=False)
  File "/home/om/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'ip -json -det address'
2025-03-13 14:58:26,772 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target', 'network-online.target']
**After=['klipper.service', 'system.slice', 'sysinit.target', 'network-online.target', 'systemd-journald.socket', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om
2025-03-13 14:58:26,772 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-03-13 14:58:26,773 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-03-13 14:58:26,780 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-03-13 14:58:26,784 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-03-13 14:58:26,786 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', '-.mount', 'system.slice']
**After=['-.mount', 'basic.target', 'systemd-journald.socket', 'klipper-mcu.service', 'system.slice', 'network-online.target', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-13 14:58:26,787 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-03-13 14:58:26,804 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2025-03-13 14:58:26,816 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-03-13 14:58:26,979 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.117
2025-03-13 14:58:26,986 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.117
2025-03-13 14:58:28,233 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2025-03-13 14:58:28,281 [git_deploy.py:log_repo_info()] - Git Repo moonraker Detected:
Owner: Arksine
Repository Name: moonraker
Path: /home/om/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Recovery URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Upstream Commit SHA: 4eb23ef2817dc56e9a8a2bf81e1a011ee27888e3
Current Version: v0.8.0-268-ga23187b4
Upstream Version: v0.9.3-67-g4eb23ef2
Rollback Commit: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Rollback Branch: master
Rollback Version: v0.8.0-268-ga23187b4
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 220
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
2025-03-13 14:58:28,323 [git_deploy.py:log_repo_info()] - Git Repo klipper Detected:
Owner: Klipper3d
Repository Name: klipper
Path: /home/om/klipper
Remote: origin
Branch: master
Remote URL: https://github.com/Klipper3d/klipper.git
Recovery URL: https://github.com/Klipper3d/klipper.git
Current Commit SHA: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Upstream Commit SHA: 47aa28e5300d75764add52e34b23b1804147626c
Current Version: v0.12.0-85-gd785b396
Upstream Version: v0.12.0-457-g47aa28e5
Rollback Commit: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Rollback Branch: master
Rollback Version: v0.12.0-85-gd785b396
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 372
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']
2025-03-13 14:58:28,329 [base_deploy.py:log_info()] - PackageKit: Next refresh in: 5 Days, 23 Hours, 3 Minutes, 53 Seconds
2025-03-13 14:58:28,330 [base_deploy.py:log_info()] - Git Repo moonraker: Next refresh in: 5 Days, 23 Hours, 3 Minutes, 56 Seconds
2025-03-13 14:58:28,331 [base_deploy.py:log_info()] - Git Repo klipper: Next refresh in: 5 Days, 23 Hours, 4 Minutes, 17 Seconds
2025-03-13 14:58:28,335 [git_deploy.py:_check_repo_status()] - Git Repo klipper-backup: path '/home/om/klipper-backup' is not a valid git repo
2025-03-13 14:58:28,336 [git_deploy.py:refresh_repo_state()] - Git Repo klipper-backup: Initialization failure
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 365, in refresh_repo_state
    self._verify_repo()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 776, in _verify_repo
    raise self.server.error(
moonraker.utils.ServerError: Git Repo klipper-backup: repo not initialized
2025-03-13 14:58:28,339 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 57, in refresh
    await self._update_repo_state()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 63, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 365, in refresh_repo_state
    self._verify_repo()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 776, in _verify_repo
    raise self.server.error(
moonraker.utils.ServerError: Git Repo klipper-backup: repo not initialized
2025-03-13 14:58:28,351 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/om/printer_data/comms/moonraker.sock'
2025-03-13 14:58:28,352 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: Go3D
2025-03-13 14:58:28,355 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-03-13 14:58:28,611 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-13 14:58:28,806 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['basic.target', 'system.slice', 'sysinit.target', 'network-online.target', '-.mount', 'systemd-journald.socket', 'klipper-mcu.service']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-13 14:58:29,065 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396a-dirty
2025-03-13 14:58:29,114 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-13 15:36:56,071 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-13 15:36:56,308 [job_state.py:_handle_started()] - Job state initialized: standby
2025-03-13 15:36:56,595 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-13 15:36:57,061 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-13 15:37:07,550 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-13 15:37:07,573 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 4.90ms
2025-03-13 15:37:07,574 [websockets.py:open()] - Websocket Opened: ID: 547928764576, Proxied: False, User Agent: , Host Name: 127.0.0.1
2025-03-13 15:37:07,652 [websockets.py:_handle_identify()] - Websocket 547928764576 Client Identified - Name: KlipperScreen, Version: v0.4.5-10-43ad9fc6-dirty, Type: display
2025-03-13 15:37:08,342 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
-------------------- Log Start | Thu Mar 13 10:15:14 2025 --------------------
data_path: /home/om/printer_data
is_default_data_path: False
config_file: /home/om/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 3060fe1b3f574a95a5a343c6fc66396c
unix_socket_path: /home/om/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/om/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/om/moonraker-env/bin/python /home/om/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2025-03-13 15:45:14,759 [confighelper.py:read_file()] - Configuration File '/home/om/printer_data/config/moonraker.conf' parsed, total size: 2375 B
2025-03-13 15:45:14,759 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
max_upload_size = 1024
klippy_uds_address = ~/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing = False

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[announcements]
subscriptions = 
	mainsail

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

#################################################################
All Configuration Files:
/home/om/printer_data/config/moonraker.conf
#################################################################
2025-03-13 15:45:15,288 [server.py:load_component()] - Component (secrets) loaded
2025-03-13 15:45:15,323 [server.py:load_component()] - Component (template) loaded
2025-03-13 15:45:15,346 [server.py:load_component()] - Component (klippy_connection) loaded
2025-03-13 15:45:17,670 [server.py:load_component()] - Component (application) loaded
2025-03-13 15:45:17,737 [server.py:load_component()] - Component (websockets) loaded
2025-03-13 15:45:18,030 [server.py:load_component()] - Component (dbus_manager) loaded
2025-03-13 15:45:18,130 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 185
2025-03-13 15:45:18,150 [server.py:load_component()] - Component (database) loaded
2025-03-13 15:45:18,226 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-03-13 15:45:18,339 [server.py:load_component()] - Component (file_manager) loaded
2025-03-13 15:45:18,351 [server.py:load_component()] - Component (klippy_apis) loaded
2025-03-13 15:45:18,932 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: add5f1c6
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.4
  total_memory: 880328
  memory_units: kB

***sd_info***
  manufacturer_id: 03
  manufacturer: Sandisk
  oem_id: 5344
  product_name: SK32G
  product_revision: 8.5
  serial_number: 83e73685
  manufacturer_date: 6/2024
  capacity: 29.7 GiB
  total_bytes: 31914983424

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-03-13 15:45:18,949 [server.py:load_component()] - Component (shell_command) loaded
2025-03-13 15:45:18,949 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-03-13 15:45:18,966 [server.py:load_component()] - Component (machine) loaded
2025-03-13 15:45:18,973 [server.py:load_component()] - Component (data_store) loaded
2025-03-13 15:45:18,983 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2025-03-13 15:45:18,986 [server.py:load_component()] - Component (proc_stats) loaded
2025-03-13 15:45:18,993 [server.py:load_component()] - Component (job_state) loaded
2025-03-13 15:45:19,012 [server.py:load_component()] - Component (job_queue) loaded
2025-03-13 15:45:19,031 [server.py:load_component()] - Component (http_client) loaded
2025-03-13 15:45:19,050 [server.py:load_component()] - Component (announcements) loaded
2025-03-13 15:45:19,059 [server.py:load_component()] - Component (webcam) loaded
2025-03-13 15:45:19,067 [server.py:load_component()] - Component (extensions) loaded
2025-03-13 15:45:19,125 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://.*\.local
http://.*\.lan
2025-03-13 15:45:19,141 [server.py:load_component()] - Component (authorization) loaded
2025-03-13 15:45:19,288 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/om/moonraker-env
2025-03-13 15:45:19,299 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/om/klippy-env
2025-03-13 15:45:19,315 [server.py:load_component()] - Component (update_manager) loaded
2025-03-13 15:45:19,333 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-03-13 15:45:19,346 [server.py:load_component()] - Component (history) loaded
2025-03-13 15:45:19,350 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-03-13 15:45:19,380 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-03-13 15:45:19,517 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-03-13 15:45:19,519 [machine.py:validation_init()] - Installation version in database up to date
2025-03-13 15:45:20,405 [machine.py:check_virt_status()] - No Virtualization Detected
2025-03-13 15:45:20,439 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.117
2025-03-13 15:45:20,446 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.117
2025-03-13 15:45:20,592 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'sysinit.target', 'system.slice']
**After=['network-online.target', 'systemd-journald.socket', 'sysinit.target', 'basic.target', 'system.slice', 'klipper.service']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/om/printer_data/systemd/moonraker.env
**ExecStart=/home/om/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=om
2025-03-13 15:45:20,592 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-03-13 15:45:20,593 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-03-13 15:45:20,598 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-03-13 15:45:20,599 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.117
2025-03-13 15:45:20,603 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-03-13 15:45:20,605 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['basic.target', 'system.slice', 'sysinit.target', 'network-online.target', '-.mount', 'systemd-journald.socket', 'klipper-mcu.service']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-13 15:45:20,605 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-03-13 15:45:20,606 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2025-03-13 15:45:20,613 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-03-13 15:45:21,316 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2025-03-13 15:45:21,352 [git_deploy.py:log_repo_info()] - Git Repo moonraker Detected:
Owner: Arksine
Repository Name: moonraker
Path: /home/om/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Recovery URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Upstream Commit SHA: 4eb23ef2817dc56e9a8a2bf81e1a011ee27888e3
Current Version: v0.8.0-268-ga23187b4
Upstream Version: v0.9.3-67-g4eb23ef2
Rollback Commit: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Rollback Branch: master
Rollback Version: v0.8.0-268-ga23187b4
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 220
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
2025-03-13 15:45:21,386 [git_deploy.py:log_repo_info()] - Git Repo klipper Detected:
Owner: Klipper3d
Repository Name: klipper
Path: /home/om/klipper
Remote: origin
Branch: master
Remote URL: https://github.com/Klipper3d/klipper.git
Recovery URL: https://github.com/Klipper3d/klipper.git
Current Commit SHA: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Upstream Commit SHA: 47aa28e5300d75764add52e34b23b1804147626c
Current Version: v0.12.0-85-gd785b396
Upstream Version: v0.12.0-457-g47aa28e5
Rollback Commit: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Rollback Branch: master
Rollback Version: v0.12.0-85-gd785b396
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 372
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['klippy/extras/gcode_shell_command.py']
2025-03-13 15:45:21,394 [base_deploy.py:log_info()] - PackageKit: Next refresh in: 5 Days, 22 Hours, 17 Minutes
2025-03-13 15:45:21,395 [base_deploy.py:log_info()] - Git Repo moonraker: Next refresh in: 5 Days, 22 Hours, 17 Minutes, 3 Seconds
2025-03-13 15:45:21,395 [base_deploy.py:log_info()] - Git Repo klipper: Next refresh in: 5 Days, 22 Hours, 17 Minutes, 24 Seconds
2025-03-13 15:45:21,398 [git_deploy.py:_check_repo_status()] - Git Repo klipper-backup: path '/home/om/klipper-backup' is not a valid git repo
2025-03-13 15:45:21,399 [git_deploy.py:refresh_repo_state()] - Git Repo klipper-backup: Initialization failure
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 365, in refresh_repo_state
    self._verify_repo()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 776, in _verify_repo
    raise self.server.error(
moonraker.utils.ServerError: Git Repo klipper-backup: repo not initialized
2025-03-13 15:45:21,399 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 57, in refresh
    await self._update_repo_state()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 63, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 365, in refresh_repo_state
    self._verify_repo()
  File "/home/om/moonraker/moonraker/components/update_manager/git_deploy.py", line 776, in _verify_repo
    raise self.server.error(
moonraker.utils.ServerError: Git Repo klipper-backup: repo not initialized
2025-03-13 15:45:21,410 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/om/printer_data/comms/moonraker.sock'
2025-03-13 15:45:21,417 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: Go3D
2025-03-13 15:45:21,423 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-03-13 15:45:21,677 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-03-13 15:45:21,834 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', '-.mount', 'sysinit.target']
**After=['system.slice', '-.mount', 'network-online.target', 'basic.target', 'sysinit.target', 'systemd-journald.socket', 'klipper-mcu.service']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/om/printer_data/systemd/klipper.env
**ExecStart=/home/om/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/om/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=om
2025-03-13 15:45:22,091 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396a-dirty
2025-03-13 15:45:22,150 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-03-13 15:45:22,153 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-03-13 15:45:22,409 [job_state.py:_handle_started()] - Job state initialized: standby
2025-03-13 15:45:22,678 [klippy_connection.py:_check_ready()] - Klippy ready
2025-03-13 15:45:23,155 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-03-13 15:45:24,116 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-03-13 15:45:24,141 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 5.97ms
2025-03-13 15:45:24,142 [websockets.py:open()] - Websocket Opened: ID: 547321351184, Proxied: False, User Agent: , Host Name: 127.0.0.1
2025-03-13 15:45:24,405 [websockets.py:_handle_identify()] - Websocket 547321351184 Client Identified - Name: KlipperScreen, Version: v0.4.5-10-43ad9fc6-dirty, Type: display
2025-03-13 15:45:25,018 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
